"""Configuration models, store, and validation primitives."""

from .group_paths import ResolvedGroupPaths, resolve_group_paths
from .issues import ValidationFailed, ValidationIssue
from .models import (
    AgencyConfig,
    ParsedConfig,
    PromptSelector,
    parse_config,
    validate_config,
)
from .patches import (
    AgencySettingsPatch,
    AgentProfilePatch,
    AgentRuntimePatch,
    GroupCreateStatePatch,
    GroupDispatchPatch,
    GroupSettingsPatch,
    GroupSettingsStatePatch,
    create_agent_instance,
    create_group,
    create_group_state,
    delete_group,
    dismiss_tip,
    hide_all_tips,
    patch_agency_settings,
    patch_agent_profile,
    patch_agent_runtime,
    patch_group_dispatch,
    patch_group_settings,
    patch_group_settings_state,
    patch_memory_channels,
    register_agent_prompt,
    remove_agent_instance,
    replace_agent_routines,
    unregister_agent_prompt,
)
from .paths import DirectoryPreparationError, is_symlink_or_reparse, prepare_writable_directory
from .store import (
    ABSENT_REVISION,
    ConfigFileSnapshot,
    ConfigConflictError,
    ConfigSnapshot,
    ConfigStore,
    config_revision,
    load_config_snapshot,
)

__all__ = [
    "AgencyConfig",
    "ABSENT_REVISION",
    "AgencySettingsPatch",
    "AgentProfilePatch",
    "AgentRuntimePatch",
    "ConfigFileSnapshot",
    "ConfigConflictError",
    "ConfigSnapshot",
    "ConfigStore",
    "DirectoryPreparationError",
    "GroupCreateStatePatch",
    "GroupDispatchPatch",
    "GroupSettingsPatch",
    "GroupSettingsStatePatch",
    "ParsedConfig",
    "PromptSelector",
    "ResolvedGroupPaths",
    "ValidationFailed",
    "ValidationIssue",
    "config_revision",
    "create_agent_instance",
    "create_group",
    "create_group_state",
    "delete_group",
    "dismiss_tip",
    "hide_all_tips",
    "is_symlink_or_reparse",
    "load_config_snapshot",
    "patch_agency_settings",
    "patch_agent_profile",
    "patch_agent_runtime",
    "patch_group_dispatch",
    "patch_group_settings",
    "patch_group_settings_state",
    "patch_memory_channels",
    "parse_config",
    "prepare_writable_directory",
    "register_agent_prompt",
    "remove_agent_instance",
    "replace_agent_routines",
    "resolve_group_paths",
    "unregister_agent_prompt",
    "validate_config",
]
