"""Configuration models, store, and validation primitives."""

from .team_paths import ResolvedTeamPaths, resolve_team_paths
from .issues import ValidationFailed, ValidationIssue
from .models import (
    AgencyConfig,
    ParsedConfig,
    PromptSelector,
    parse_config,
    validate_config,
)
from .patches import (
    AgencySettingsPatch,
    AgentProfilePatch,
    AgentRuntimePatch,
    TeamCreateStatePatch,
    TeamDispatchPatch,
    TeamSettingsPatch,
    TeamSettingsStatePatch,
    create_agent_instance,
    create_team,
    create_team_state,
    delete_team,
    dismiss_tip,
    hide_all_tips,
    patch_agency_settings,
    patch_agent_profile,
    patch_agent_runtime,
    patch_team_dispatch,
    patch_team_settings,
    patch_team_settings_state,
    patch_memory_channels,
    register_agent_prompt,
    remove_agent_instance,
    replace_agent_routines,
    unregister_agent_prompt,
)
from .paths import DirectoryPreparationError, is_symlink_or_reparse, prepare_writable_directory
from .store import (
    ABSENT_REVISION,
    ConfigFileSnapshot,
    ConfigConflictError,
    ConfigSnapshot,
    ConfigStore,
    config_revision,
    load_config_snapshot,
)

__all__ = [
    "AgencyConfig",
    "ABSENT_REVISION",
    "AgencySettingsPatch",
    "AgentProfilePatch",
    "AgentRuntimePatch",
    "ConfigFileSnapshot",
    "ConfigConflictError",
    "ConfigSnapshot",
    "ConfigStore",
    "DirectoryPreparationError",
    "TeamCreateStatePatch",
    "TeamDispatchPatch",
    "TeamSettingsPatch",
    "TeamSettingsStatePatch",
    "ParsedConfig",
    "PromptSelector",
    "ResolvedTeamPaths",
    "ValidationFailed",
    "ValidationIssue",
    "config_revision",
    "create_agent_instance",
    "create_team",
    "create_team_state",
    "delete_team",
    "dismiss_tip",
    "hide_all_tips",
    "is_symlink_or_reparse",
    "load_config_snapshot",
    "patch_agency_settings",
    "patch_agent_profile",
    "patch_agent_runtime",
    "patch_team_dispatch",
    "patch_team_settings",
    "patch_team_settings_state",
    "patch_memory_channels",
    "parse_config",
    "prepare_writable_directory",
    "register_agent_prompt",
    "remove_agent_instance",
    "replace_agent_routines",
    "resolve_team_paths",
    "unregister_agent_prompt",
    "validate_config",
]
